### ISSUE TITLE
Static page cannot load the user info starting from version 2.6.38

### ISSUE THREAD

**Issue by Chenalejandro** [stack-auth/stack-auth#384]
Steps to reproduce:

1. clone repo https://github.com/Chenalejandro/stackbug
2. pnpm dev
3. go to localhost:3000, click sign in and then enter the credentials to sign in

Expected: redirected back to the root page, where the user button will be shown
Actual: redirect back to the root page, but the sign in button is still there

If we go to localhost:3000/nonstaticpage, we can see the user button because it is a dynamic page. The root page is static.

You can downgrade @stackframe/stack to 2.6.37 and confirm that you can see the user button even in a static page.

This bug happens in both dev and production.

I cannot make the page.tsx a client component (with "use client";) since my component is an async function that fetches some data and statically generate the page with that data.

**Comment by Chenalejandro** [comment]
Update: Using pnpm patch to remove this line https://github.com/stack-auth/stack/commit/9f73738d12f3c0acf16a75d48b83be1454a7d00d#diff-146a911308a31afb51a555977852fa6e957ca4c7a89f82317429c30afe435b9aR189 fixes the issue.

**Comment by fomalhautb** [comment]
This should be fixed in the newest version

**Comment by Chenalejandro** [comment]
I cannot find the pull request that fixes this issue. I tried running the latest version of stack with the reproduction repo, and the issue still exists.

**Comment by madster456** [comment]
> I cannot find the pull request that fixes this issue. I tried running the latest version of stack with the reproduction repo, and the issue still exists.

I am unsure of where this was fixed. Cannot seem to find it. But updating to the latest version does make this work. 

---

<img src="https://stack-auth.com/_next/static/media/stack-auth-logo.84c18f5e.svg" width="200" />
